name: Deploy to Hexo

on:
  workflow_dispatch:
  push:
    branches:
      - blog

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Hexo CI
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g

      - name: Install plugins
        run: |
          npm install

      - name: Deploy
        run: |
          hexo clean && hexo g
          cd ./public
          git init
          git branch -m main
          git config user.name "${{secrets.GIT_NAME}}"
          git config user.email "${{secrets.GIT_EMAIL}}"
          git add .
          git commit -m "Update"
          git push --force --quiet "https://${{secrets.GH_TOKEN}}@${{secrets.GH_REF}}" main:main
