name: Download Daily Wallpaper

on:
  workflow_dispatch:
  push:
    branches:
      - blog
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
   
      - name: Download Unslpash daily image
        run: |
          npm i -g unsplash-wallpaper
          cd ./themes/butterfly/source/img/
          unsplash-wallpaper --featured wallpapers --daily --width 4096 --height 2160
          mv -f wallpaper-photo*.jpg unsplash_wallpaper.jpg
          
      - name: Download Bing wallpaper
        run: |
          cd ./themes/butterfly/source/img/
          curl https://bing.ioliu.cn/v1/rand?w=4096&h=2160 -o bing_wallpaper.jpg
          
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: blog
          message: 'Download Daily Wallpaper'
