name: Download Bing Wallpaper

on:
  workflow_dispatch:
  push:
    branches:
      - blog
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

          
      - name: Download Bing Wallpaper
        run: |
          curl https://bing.ioliu.cn/v1/rand -o banner.jpg
          
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: blog
          message: 'Download Unslpash Daily Image'
