name: 自动部署 Hexo

on:
  workflow_dispatch:
  push:
    branches:
      - blog
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: 开始运行
        uses: actions/checkout@v2.3.4

      - name: 设置 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安装 Hexo CI
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g

      - name: 安装插件
        run: |
          npm install
      - name: 下载Unsplash每日图片
        run: |
          npm i -g unsplash-wallpaper
          unsplash-wallpaper --daily --dir "./themes/butterfly/source/img/"

      - name: 部署博客
        run: |
          hexo clean && hexo g
          cd ./public
          git init
          git branch -m main
          git config user.name "${{secrets.GIT_NAME}}"
          git config user.email "${{secrets.GIT_EMAIL}}"
          git add .
          git commit -m "Update"
          git push --force --quiet "https://${{secrets.GH_TOKEN}}@${{secrets.GH_REF}}" main:main
